Web.ManagerTask/Models/Projeto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyTask.Models;

public partial class Projeto
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [Display(Name = "Nome:")]
    public string? NomeProjeto { get; set; }

    [Display(Name = "Descrição:")]
    public string? DescricaoProjeto { get; set; }

    public DateTime? DataCriacaoProjeto { get; set; } = DateTime.Now;

    public bool Status { get; set; } = false;

    public int? UsuarioCriadorId { get; set; }

    public virtual ICollection<Tarefa> Tarefas { get; set; } = new List<Tarefa>();

    public virtual Usuario? UsuarioCriador { get; set; }
}

Web.ManagerTask/Models/ProjetoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyTask.Models;

public partial class ProjetoViewModel
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "O campo {0} é obrigatório")]
    [Display(Name = "Nome:")]
    public string? NomeProjeto { get; set; }

    [Display(Name = "Descrição:")]
    public string? DescricaoProjeto { get; set; }

    public DateTime? DataCriacaoProjeto { get; set; } = DateTime.Now;

    public bool Status { get; set; } = false;

    public int? UsuarioCriadorId { get; set; }

    public virtual ICollection<TarefaViewModel> Tarefas { get; set; } = new List<TarefaViewModel>();

    public virtual Usuario? UsuarioCriador { get; set; }
}

Web.ManagerTask/Controllers/ProjetoController.cs
using ManagerTask.Domain.Entities;
using ManagerTask.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyTask.Models;

namespace Web.ManagerTask.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly IProjetoService _service;

        public ProjetoController(IProjetoService service)
            => _service = service;


        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var projetos = await _service.ListProjectTask();

            return View(projetos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(ProjetoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Erro = "Erro ao criar projeto!";
                return View(model);
            }


            var projeto = new Projeto()
            {
                NomeProjeto = model.NomeProjeto,
                Status = model.Status,
                Tarefas = new List<Tarefa>(),
                DescricaoProjeto = model.DescricaoProjeto,
                DataCriacaoProjeto = DateTime.Now,
                UsuarioCriadorId = model.UsuarioCriadorId

            };


            await _service.AddAsync(projeto);

            ViewBag.Sucesso = "Projeto cadastrado com sucesso!";

            return View("Lista", await _service.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var projeto = await _service.GetByIdAsync(id);

            if (projeto == null)
                ViewBag.Erro = "Erro ao Recuperar Projeto";


            return View(projeto);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(ProjetoViewModel model)
        {
            var projeto = new Projeto()
            {
                Id = model.Id,
                NomeProjeto = model.NomeProjeto,
                Status = model.Status,
                Tarefas = new List<Tarefa>(),
                DescricaoProjeto = model.DescricaoProjeto,
                DataCriacaoProjeto = DateTime.Now,
                UsuarioCriadorId = model.UsuarioCriadorId

            };

            await _service.UpdateAsync(projeto);
            return RedirectToAction("Lista");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var tarefas = await _service.ListTaskByProject(id);

            foreach (var tarefa in tarefas)
            {
                tarefa.Status = 0;
            }


            var projeto = await _service.GetByIdAsync(id);

            if (projeto == null)
            {
                ViewBag.Erro = "Erro ao excluir";
              
            }

            await _service.DeleteAsync(projeto);
            ViewBag.Sucesso = "Projeto Excluído com sucesso !";

            return RedirectToAction("Lista");
        }


        [HttpGet]
        public async Task<IActionResult> listarTarefasPorProjeto(int id)
        {
            if (id == null)
            {
                ViewBag.Erro = "Não foi possível recuperar as Tafefas !";
                return View();
            }

            try
            {
                var tarefas = await _service.ListTaskByProject(id);

                if (tarefas.Count != 0)
                {
                    ViewBag.ProjetoId = tarefas.FirstOrDefault(x => x.ProjetoId == id)!.ProjetoId;
                    
                }
                ViewBag.ProjetoId = id;



                return View(tarefas);
            }
            catch (Exception e)
            {
                ViewBag.Erro = e.ToString();
                return View();
                throw;
            }
        }


    }
}

Web.ManagerTask/Controllers/TarefaController.cs
using System.Net;
using System.Net.Mail;
using ManagerTask.Application.Services;
using ManagerTask.Domain.Entities;
using ManagerTask.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyTask.Models;
using HistoricoAtividade = ManagerTask.Domain.Entities.HistoricoAtividade;
using Usuario = ManagerTask.Domain.Entities.Usuario;


namespace Web.ManagerTask.Controllers
{
    public class TarefaController : Controller
    {
        private readonly ITarefaService _tarefaService;
        private readonly IProjetoService _projetoService;
        private readonly UsuarioService _usuarioService;

        private readonly IConfiguration _configuration;


        public TarefaController(
            ITarefaService tarefaService,
            IProjetoService projetoService,
            UsuarioService usuarioService,
            IConfiguration configuration
            )
        {
            _tarefaService = tarefaService;
            _projetoService = projetoService;
            _usuarioService = usuarioService;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index()
        {

            try
            {
                ViewData["ProjetoId"] = new SelectList(await _projetoService.GetAllAsync(), "Id", "Nome");
                ViewData["UsuarioResponsavelId"] = new SelectList(await _usuarioService.GetAllAsync(), "Id", "Nome");

                IEnumerable<TarefaViewModel> tarefas = (IEnumerable<TarefaViewModel>)await _tarefaService.ListTaskUser();

                return View(tarefas);

            }
            catch (Exception)
            {
                ViewBag.Erro = "Erro ao Carregar Dados!";

                return View();
            }
        }


        public async Task<IActionResult> Detalhar(int? id)
        {


            if (id == null)
            {
                return NotFound();
            }


            IEnumerable<Tarefa> tarefas = (IEnumerable<Tarefa>)await _tarefaService.ListTaskUser();

            var tarefa = tarefas.FirstOrDefault(x => x.Id == id);



            if (tarefa == null)
            {
                return NotFound();
            }

            return PartialView("_DetalharTarefa", tarefa);
        }


        public async Task<IActionResult> Create(int projetoId)
        {
            ViewData["ProjetoId"] = projetoId;
            ViewData["UsuarioResponsavelId"] = new SelectList(await _usuarioService.GetAllAsync(), "Id", "Nome");

            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(TarefaViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tarefa = new Tarefa
                {
                    Titulo = model.Titulo,
                    Descricao = model.Descricao,
                    ProjetoId = model.ProjetoId,
                    UsuarioResponsavelId = model.UsuarioResponsavelId,
                };

                await _tarefaService.AddAsync(tarefa);

                Usuario? usuario = await _usuarioService.GetByIdAsync(tarefa.UsuarioResponsavelId);


                //registra cada task criada no historico de atividades
                RegistrarHistorico(tarefa);
                EnviarEmail(usuario, tarefa.Id, tarefa.Titulo);

                return RedirectToAction("listarTarefasPorProjeto", "Projeto", new { id = tarefa.ProjetoId }, ViewBag.Sucesso);

            }
            ViewBag.Erro = "Erro ao cadastrar Tarefa!";

            ViewData["UsuarioResponsavelId"] = new SelectList(await _usuarioService.GetAllAsync(), "Id", "Nome");
            return View();

        }


        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var model = await _tarefaService.GetByIdAsync(id);

            var tarefa = new TarefaViewModel()
            {
                Titulo = model.Titulo,
                Descricao = model.Descricao,
                Status = model.Status,
                ProjetoId = model.ProjetoId,
                UsuarioResponsavelId = model.UsuarioResponsavelId,
                lActive = model.LActive
            };

            if (tarefa == null)
            {
                return NotFound();
            }
            ViewData["UsuarioResponsavelId"] = new SelectList(await _usuarioService.GetAllAsync(), "Id", "Nome");
            return View(tarefa);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TarefaViewModel model)
        {


            if (ModelState.IsValid)
            {
                try
                {
                    var tarefa = new Tarefa()
                    {
                        Titulo = model.Titulo,
                        Descricao = model.Descricao,
                        Status = model.Status,
                        UsuarioResponsavelId = model.UsuarioResponsavelId,
                        LActive = model.lActive,
                        ProjetoId = model.ProjetoId
                    };

                    await _tarefaService.UpdateAsync(tarefa);
                }
                catch (DbUpdateConcurrencyException)
                {

                }
                return RedirectToAction("Index");
            }
            ViewData["UsuarioResponsavelId"] = new SelectList(await _usuarioService.GetAllAsync(), "Id", "Nome");
            
            return View();
        }

        public async Task<IActionResult> FinalizarTarefa(int id)
        {

            var tarefa = await _tarefaService.FinishTask(id);

            return RedirectToAction("listarTarefasPorProjeto", "Projeto", new { id = tarefa.ProjetoId });
        }

        public async Task<IActionResult> ReabrirTarefa(int id)
        {

            var tarefa = await _tarefaService.ReOpenTask(id);


            return RedirectToAction("listarTarefasPorProjeto", "Projeto", new { id = tarefa.ProjetoId });
        }


        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            try
            {
                var tarefa = await _tarefaService.GetByIdAsync(id);


                if (tarefa != null)
                {
                   await _tarefaService.DeleteAsync(tarefa);
                }

                return RedirectToAction("listarTarefasPorProjeto", "Projeto", new { id = tarefa.ProjetoId });
            }
            catch (Exception ex)
            {
                ViewBag.Erro = "Erro ao Excluir tarefa, " + ex.Message;
                return RedirectToAction("Lista", "Projeto" );

            }
        }



        public void EnviarEmail(Usuario usuario, int tarefaId, string tarefaTitulo)
        {
            var smtpServer = _configuration["EmailSettings:SmtpServer"];
            var port = int.Parse(_configuration["EmailSettings:Port"]);
            var userName = _configuration["EmailSettings:UserName"];
            var password = _configuration["EmailSettings:Password"];
            var enableSsl = bool.Parse(_configuration["EmailSettings:EnableSsl"]);

            var destinatario = usuario.Email;
            var assunto = "Manager Task -  Nova Tarefa";
            var corpo = @"
                                <!DOCTYPE html>
                                <html lang=""pt"">
                                <head>
                                    <meta charset=""UTF-8"">
                                    <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"">
                                    <title>Email Template</title>
                                    <style>
                                       body {
                                              font-family: Arial, sans-serif;
                                              padding: 10px;
                                            }
                                            .container {
                                              max-width: 400px;
                                              background-color: #d3dfc3;
                                              padding: 20px;
                                              border-radius: 10px;
                                              box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
                                            }
                                            .titulo {
                                              font-size: 18px;
                                              font-weight: bold;
                                            }
                                            .conteudo {
                                              font-size: 16px;
                                              border-bottom: absoluteove;
                                              border: auto-flow;
                                            }
                                            .corpo {
                                              font-size: 18px;
                                              margin-bottom: 20px;
                                            }


                                    </style>
                                </head>
                                <body>
                                    <div class=""container"">" +
                                @"<p class=""corpo"">Olá, " + usuario.Nome + "</p>" +
                                   @"<p class=""conteudo"">A tarefa <span class=""titulo"">" + tarefaId + " - " + tarefaTitulo + "</span> foi atribuída a você!</p></div></body></html>";


            using (var mensagem = new MailMessage(userName, destinatario))
            using (var clienteSmtp = new SmtpClient(smtpServer, port))
            {
                clienteSmtp.Credentials = new NetworkCredential(userName, password);
                clienteSmtp.EnableSsl = enableSsl;

                mensagem.Subject = assunto;

Web.ManagerTask/Views/Projeto/Cadastrar.cshtml
@model MyTask.Models.ProjetoViewModel

<div class="text-center">
    <h1 class="display-4">Cadastrar Projetos</h1>
</div>


<div>
    <form asp-action="Cadastrar">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NomeProjeto" class="control-label">Nome</label>
            <input asp-for="NomeProjeto" class="form-control" />
            <span asp-validation-for="NomeProjeto" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <textarea class="form-control" asp-for="DescricaoProjeto" rows="3"></textarea>
        </div>


        <br />

        <div class="form-group d-grid gap-2">
            <input type="submit" value="Salvar" class="btn btn-primary btn-block" />
            <a asp-action="lista" class="btn btn-secondary btn-block">Voltar</a>

        </div>
    </form>
</div>

Web.ManagerTask/Views/Projeto/Editar.cshtml
@model ManagerTask.Domain.Entities.Projeto

<div class="text-center">
    <h1 class="display-4">Editar Projeto</h1>
</div>

<form asp-action="Editar">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label class="control-label">Nome</label>
        <input asp-for="NomeProjeto" class="form-control" />
        <span asp-validation-for="NomeProjeto" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label class="control-label">Descrição</label>
        <input asp-for="DescricaoProjeto" class="form-control" />
        <span asp-validation-for="DescricaoProjeto" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Salvar" class="btn btn-primary" />
    </div>
</form>

Web.ManagerTask/Views/Projeto/Lista.cshtml
 @model IEnumerable<ManagerTask.Domain.Entities.Projeto>

<div class="row">
    <div class="col-9"></div>
   <div class="col-3">
        @if (ViewBag.Sucesso != null && ViewBag.Erro == null)
        {
            <div id="alertaSuccesso" class="alert alert-success">
                <div>
                    @ViewBag.Sucesso
                </div>
            </div>
        }
        @if (ViewBag.Erro != null && ViewBag.Sucesso == null)
        {
            <div id="alertaErro" class="alert alert-danger">
                <div>
                    @ViewBag.Erro
                </div>
            </div>
        }
   </div>
</div>


<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary btn-block btn-lg" role="button" asp-controller="Projeto" asp-action="Cadastrar">Cadastrar</a>
    </div>
    <br />
    <h1 class="display-4">Listagem de Projetos</h1>
    <br />
   
    <table class="table table-bordered table-sm">
        <thead class="thead-dark">

            <tr>
                <th>
                    Projeto
                </th>
                <th>
                    Descrição
                </th>
                <th>
                    Data da Criação
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeProjeto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescricaoProjeto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DataCriacaoProjeto)
                    </td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                            <a class="btn btn-sm btn-secondary" asp-route-id="@item.Id" asp-action="listarTarefasPorProjeto">Tarefas</a>
                            <a type="button" class="btn btn-primary" asp-route-id="@item.Id" asp-action="Editar">Editar</a>
                            <a href="javascript:" projeto-id="@item.Id" type="button" class="btn btn-danger btn-excluir-projeto">Excluir</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>


    <div id="modalExcluirProjeto" class="modal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Atenção ! </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <h6>Desejar mesmo excluir esse projeto ? todas Tarefas Associadas serão finalizadas !</h6>
                    </div>
                    <br />

                    <div class="d-grid gap-2">
                        <a href="javascript:" id="ProjetoConfirmaExclusao" class="btn btn-danger">Remover</a>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
                            Cancelar
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </div>

Web.ManagerTask/Views/Projeto/listarTarefasPorProjeto.cshtml
@model IEnumerable<ManagerTask.Domain.Entities.Tarefa>

@{
    foreach(var item in Model)
    {
        ViewBag.ProjetoId = item.ProjetoId;
    }

}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listagem de Tarefas</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        .task-table {
            margin-top: 20px;
        }

            .task-table th {
                text-align: center;
            }

        .btn-group {
            display: flex;
            justify-content: center;
        }

     

        .custom-tooltip .tooltip-inner {
            background-color: #007bff; /* Cor de fundo */
            color: #fff; /* Cor do texto */
            border-radius: 4px; /* Borda arredondada */
            padding: 8px 12px; /* Espaçamento interno */
            font-size: 14px; /* Tamanho da fonte */
        }
    </style>
</head>
<body>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary btn-block btn-lg" role="button" asp-route-projetoId="@ViewBag.ProjetoId" asp-controller="Tarefa" asp-action="Create">
            <i class="fas fa-plus-circle"></i> Nova Tarefa
        </a>
    </div>
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2 class="text-center mb-4">BackLog</h2>
                <table class="table table-bordered table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">Tarefa</th>
                        
                            <th></th>
                          
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Where(x => x.Status == 1))
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Titulo)</td>
                       
                                <td>
                                    

                                        <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                                        <a tarefa-id="@item.Id" class="btn btn-primary btn-sm btn-detalhar-tarefa"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Detalhar tarefa">
                                            <i class="fas fa-eye"></i> 
                                        </a>
                                        <a  asp-action="FinalizarTarefa" asp-controller="Tarefa" asp-route-id="@item.Id" 
                                            class="btn btn-success btn-sm"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Finalizar Tarefa">
                                            <i class="fas fa-check-circle"></i> 
                                        </a>


                                        <a class="btn btn-danger btn-sm btn-excluir-tarefa"
                                           tarefa-id="@item.Id"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Excluir">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                   
                                    </div>
                                 
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <h2 class="text-center mb-4">Done</h2>
                <table class="table table-bordered table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th class="text-center">Tarefa</th>
                    
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Where(x => x.Status == 0))
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.Titulo)</td>
                  
                                <td>
                                    <div class="btn-group" role="group"> 
                                        <a tarefa-id="@item.Id" class="btn btn-primary btn-sm btn-detalhar-tarefa"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Detalhar Tarefa"><i class="fas fa-eye"></i></a>

                                        <a asp-action="ReabrirTarefa" asp-controller="Tarefa" asp-route-id="@item.Id" class="btn btn-warning btn-sm"
                                           data-bs-toggle="tooltip" data-bs-placement="top" title="Reabrir Tarefa">
                                            <i class="fas fa-redo"></i> 
                                        </a>
                                        <a class="btn btn-danger btn-sm btn-excluir-tarefa"
                                                tarefa-id="@item.Id"
                                                data-bs-toggle="tooltip" data-bs-placement="top" title="Excluir">
                                            <i class="fas fa-trash"></i>
                                        </a>

                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div id="modalDetalharTarefa" class="modal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div id="detalheTarefas"></div>
                </div>
            </div>
        </div>
    </div>


    <div id="modalExcluirTarefa" class="modal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Atenção ! </h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    </button>
                </div>
                <div class="modal-body">
                    <div>
                        <h6>Desejar mesmo excluir essa Tarefa ?</h6>
                    </div>
                    <br />

                    <div class="d-grid gap-2">
                        <a href="javascript:" class="btn btn-danger btn btn-confirmar-excluir-tarefa">Remover</a>
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" aria-label="Close">
                            Cancelar
                        </button>
                    </div>
                </div>

            </div>
        </div>
    </div>



    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>