Web.ManagerTask/Controllers/ProjetoController.cs
using ManagerTask.Domain.Entities;
using ManagerTask.Domain.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyTask.Models;

namespace Web.ManagerTask.Controllers
{
    public class ProjetoController : Controller
    {
        private readonly IProjetoService _service;

        public ProjetoController(IProjetoService service)
            => _service = service;


        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var projetos = await _service.ListProjectTask();

            return View(projetos);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(ProjetoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Erro = "Erro ao criar projeto!";
                return View(model);
            }


            var projeto = new Projeto()
            {
                NomeProjeto = model.NomeProjeto,
                Status = model.Status,
                Tarefas = new List<Tarefa>(),
                DescricaoProjeto = model.DescricaoProjeto,
                DataCriacaoProjeto = DateTime.Now,
                UsuarioCriadorId = model.UsuarioCriadorId

            };


            await _service.AddAsync(projeto);

            ViewBag.Sucesso = "Projeto cadastrado com sucesso!";

            return View("Lista", await _service.GetAllAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var projeto = await _service.GetByIdAsync(id);

            if (projeto == null)
                ViewBag.Erro = "Erro ao Recuperar Projeto";


            return View(projeto);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(ProjetoViewModel model)
        {
            var projeto = new Projeto()
            {
                Id = model.Id,
                NomeProjeto = model.NomeProjeto,
                Status = model.Status,
                Tarefas = new List<Tarefa>(),
                DescricaoProjeto = model.DescricaoProjeto,
                DataCriacaoProjeto = DateTime.Now,
                UsuarioCriadorId = model.UsuarioCriadorId

            };

            await _service.UpdateAsync(projeto);
            return RedirectToAction("Lista");
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            var tarefas = await _service.ListTaskByProject(id);

            foreach (var tarefa in tarefas)
            {
                tarefa.Status = 0;
            }


            var projeto = await _service.GetByIdAsync(id);

            if (projeto == null)
            {
                ViewBag.Erro = "Erro ao excluir";
              
            }

            await _service.DeleteAsync(projeto);
            ViewBag.Sucesso = "Projeto Excluído com sucesso !";

            return RedirectToAction("Lista");
        }


        [HttpGet]
        public async Task<IActionResult> listarTarefasPorProjeto(int id)
        {
            if (id == null)
            {
                ViewBag.Erro = "Não foi possível recuperar as Tafefas !";
                return View();
            }

            try
            {
                var tarefas = await _service.ListTaskByProject(id);

                if (tarefas.Count != 0)
                {
                    ViewBag.ProjetoId = tarefas.FirstOrDefault(x => x.ProjetoId == id)!.ProjetoId;
                    
                }
                ViewBag.ProjetoId = id;



                return View(tarefas);
            }
            catch (Exception e)
            {
                ViewBag.Erro = e.ToString();
                return View();
                throw;
            }
        }


    }
}

Web.ManagerTask/Controllers/UsuarioController.cs
using ManagerTask.Application.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ManagerTask.Domain.Entities;

using Usuario = ManagerTask.Domain.Entities.Usuario;

namespace Web.ManagerTask.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly UsuarioService _service;

        public UsuarioController(UsuarioService service)
        {
            _service = service;
        }

       
        public async Task<IActionResult> lista()
        {
            //var usuarios = _context.Usuarios.Include(x => x.Tarefas).ToList();
            var usuarios = await _service.GetAllAsync();
            
            return View(usuarios);
        }

          

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> Cadastrar(global::ManagerTask.Domain.Entities.Usuario usuario)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Erro = "Erro ao cadastrar usuário";
                return RedirectToAction("lista");
            }
            await _service.AddAsync(usuario);
            return RedirectToAction("lista");

        }


        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var usuario = await _service.GetByIdAsync(id);

            return View(usuario);
        }

        [HttpPost]
        public async Task<IActionResult> Editar(int id, Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await _service.UpdateAsync(usuario);
                }
                catch (DbUpdateConcurrencyException)
                {
                    ViewBag.Erro = "Erro ao Alterar Usuário";
                }
                return RedirectToAction("lista");
            }
            return View(usuario); ;
        }


        [HttpPost]
        public async Task<IActionResult> Excluir(int id)
        {
            try
            {

                //if (usuario.Tarefas.Count >= 1)
                //{
                //    ViewBag.Erro = "Este usuário possui tarefas associadas, por favor, exclua ou conclua as tarefas associadas";

                //    return View();
                //}

                await _service.DeleteAsync(id);
                return RedirectToAction("lista");
                
            }
            catch (Exception ex)
            {
                ViewBag.Erro = "Erro ao Excluir usuario " + ex.Message;
                return View();
            }

        }

    }
}

Web.ManagerTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web.ManagerTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.ManagerTask.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">


</head>
<body>
    <header>
        <div class="collapse" id="navbarToggleExternalContent" data-bs-theme="dark">
            <div class="bg-dark p-4">
                <h5 class="text-body-emphasis h4">Collapsed content</h5>
                <span class="text-body-secondary">Toggleable via the navbar brand.</span>
            </div>
        </div>
     
        <nav class="navbar  navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciador de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projeto" asp-action="lista">Projetos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="lista">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoricoAtividades" asp-action="Lista">Histórico</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
         @RenderBody() 

          
        </main>
    </div>

@*     <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Gerenciador de tarefas 
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <a href="~/lib/jquery/dist/jquery.min.map"></a>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>